// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var PROFILE = {
  name: "Mr. Harshad Harishchandra Pakhale",
  positioning: "AI Generalist | Creative Strategist | Business Problem Solver",
  tagline: "Building modern business solutions",
  focus: [
    "AI Movie Creator / AI video generation",
    "Social media management with AI-led strategy",
    "Meta Ads & Business Meta Suite",
    "Startup strategy and zero-to-one execution"
  ],
  website: "https://vfx-dream-forge.lovable.app"
};
var CONTACT = [
  { label: "Email", value: "harshup2205@gmail.com", href: "mailto:harshup2205@gmail.com" },
  { label: "LinkedIn", value: "/in/harshad-pakhale-221hp", href: "https://www.linkedin.com/in/harshad-pakhale-221hp/" },
  { label: "Instagram", value: "@harshad.h.pakhale.01", href: "https://www.instagram.com/harshad.h.pakhale.01/" },
  { label: "WhatsApp", value: "+91 90675 72205", href: "https://wa.me/919067572205" }
];
var SERVICES = [
  { title: "AI Consultation", description: "Identify the right AI tools and workflows for your business." },
  { title: "Creative Branding", description: "Visual identity, social design, and brand systems that convert." },
  { title: "Business Strategy", description: "Frameworks to position, prioritize, and scale your operations." },
  { title: "AI Content Systems", description: "Build repeatable content engines powered by modern AI stacks." },
  { title: "Startup Support", description: "From zero-to-one execution help for early-stage founders." },
  { title: "Automation Ideas", description: "Streamline operations with smart, low-code automations." },
  { title: "Digital Growth Strategy", description: "Performance, content, and AI-led growth blueprints." }
];
var SKILLS = [
  {
    category: "AI & Productivity",
    items: ["ChatGPT", "Gemini", "Claude", "Canva AI", "Lovable", "Perplexity", "Notion AI"]
  },
  {
    category: "Creative",
    items: ["Canva", "Branding", "Social Media Design", "Presentation Design"]
  },
  {
    category: "Business & Marketing",
    items: [
      "Business Development",
      "Startup Strategy",
      "Marketing Thinking",
      "Client Handling",
      "Team Coordination"
    ]
  },
  {
    category: "Tech & Execution",
    items: ["AI-assisted Coding", "GitHub", "Vercel", "Workflow Systems", "Automation Thinking"]
  }
];
var AI_FILMS = {
  featured: "https://www.instagram.com/p/DaAyuGRoqFb/",
  gallery: [
    "https://www.instagram.com/p/DaSf25HIYcc/",
    "https://www.instagram.com/p/C8tl7cWoH4e/",
    "https://www.instagram.com/p/DaSlrNtlJF8/",
    "https://www.instagram.com/p/DaXvvBJCvo9/",
    "https://www.instagram.com/p/DaNbvIgj-s_/",
    "https://www.instagram.com/p/DaIR0sBim57/",
    "https://www.instagram.com/p/DZryk3NtKYV/",
    "https://www.instagram.com/p/DaFqao-E-Ui/",
    "https://www.instagram.com/p/DZ7VzNLAAba/",
    "https://www.instagram.com/p/DZubIZIjj60/"
  ]
};
var SOCIALS = [
  { name: "Campus Counsel", handle: "@campus_counsel_", role: "Ed-Tech Community", link: "https://www.instagram.com/campus_counsel_/" },
  { name: "XPLOREVO", handle: "@xplorevo_official", role: "Startup Media", link: "https://www.instagram.com/xplorevo_official/" },
  { name: "XTN Network", handle: "@xplorevo_tech_network", role: "Tech Network", link: "https://www.instagram.com/xplorevo_tech_network/" },
  { name: "MESWCOE E-Cell", handle: "@meswcoe_e_cell", role: "Entrepreneurship Cell", link: "https://www.instagram.com/meswcoe_e_cell/" },
  { name: "MESWCOE EIC", handle: "@meswcoe_eic", role: "Innovation Council", link: "https://www.instagram.com/meswcoe_eic/" },
  { name: "Personal", handle: "@harshad.h.pakhale.01", role: "Creator", link: "https://www.instagram.com/harshad.h.pakhale.01/" }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Harshad Pakhale's public profile: name, positioning, tagline, focus areas, website and public contact channels.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { profile: PROFILE, contact: CONTACT };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the services offered, each with a short description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "List skills and tools grouped by category (AI & Productivity, Creative, Business & Marketing, Tech & Execution). Optionally filter to one category.",
  inputSchema: {
    category: z.string().optional().describe("Optional category name filter, matched case-insensitively as a substring.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const q = category?.trim().toLowerCase();
    const groups = q ? SKILLS.filter((g) => g.category.toLowerCase().includes(q)) : SKILLS;
    return {
      content: [{ type: "text", text: JSON.stringify(groups, null, 2) }],
      structuredContent: { skills: groups }
    };
  }
});

// src/lib/mcp/tools/list-ai-films.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_ai_films_default = defineTool4({
  name: "list_ai_films",
  title: "List AI films",
  description: "List the published AI-generated short films and reels, including the featured film and the full gallery of watchable Instagram links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      featured: AI_FILMS.featured,
      gallery: AI_FILMS.gallery,
      count: AI_FILMS.gallery.length + 1
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-social-accounts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_social_accounts_default = defineTool5({
  name: "list_social_accounts",
  title: "List managed social accounts",
  description: "List the public social media accounts managed by Harshad, with handle, role and profile link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SOCIALS, null, 2) }],
    structuredContent: { accounts: SOCIALS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "neon-canvas",
  title: "Neon Canvas",
  version: "0.1.0",
  instructions: "Read-only tools for Harshad Pakhale's AI portfolio. Use `get_profile` for identity, positioning and contact channels, `list_services` for offerings, `list_skills` for tools and capabilities, `list_ai_films` for AI-generated film links, and `list_social_accounts` for managed social profiles. All data is public portfolio content.",
  tools: [
    get_profile_default,
    list_services_default,
    list_skills_default,
    list_ai_films_default,
    list_social_accounts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
